name: npm release

on:
  push:
    branches:
      - release # related github branch

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'
      - run: cd packages/core && npm i
      - run: cd packages/core && npm run test
      - run: cd packages/core && npm run build
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
          DEPLOY_DIR: packages/core
          SRC_PACKAGE_DIR: packages/core
          NODE_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        
