name: npm release

on:
  push:
    branches:
      - release # related github branch

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'
      - run: npm whoami    
      - run: pnpm install --frozen-lockfile
      - run: cd packages/core && npm run test
      - run: cd packages/core && npm run build 
      - run: cd packages/core && pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        
