name: npm release

on:
  push:
    branches:
      - release # related github branch

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'
      - run: pnpm install
      - run: cd packages/core && npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run: cd packages/core && npm run build 
      - run: cd packages/core && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
          NODE_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        
